Mehrere kleine Fehler behoben
willuhn/syntax pull request #10
Opened 2024-06-15 19:27 UTC by lenilsas

- Mandantbezogene Steuersätze nur bei diesem anzeigen
- bei Buchungstemplates wurden die Konten nicht angezeigt
- Fehler bei Kontenrahmen clonen behoben
- Bei Kontenrahmenliste Mandant Name statt id anzeigen
- Die Berechnung der Nebenbuchungssummen ging nicht bei McKoi
- Buchungsübernahme wenn kein Geschäftsjahr im zeitraum der Buchung abbrechen statt aktuell geöffnetes Geschäftsjahr nehmen.

2024-06-17 07:24 UTC, willuhn requested changes

2024-06-17 07:24 UTC, willuhn commented on src/de/willuhn/jameica/fibu/util/BuchungUtil.java
> +        params.add(new Double(start.getTime()));
Warum das Double? "getTime()" liefert doch ein "long", welches per Auto-Boxing automatisch zu einem "Long" wird.

2024-06-17 07:24 UTC, willuhn commented on src/de/willuhn/jameica/fibu/util/KontenrahmenUtil.java
> +    if (!sysdataWritable)
OK.
Ich überlege, ob es vielleicht sinnvoll wäre, *zusätzlich* noch beim Anlegen der Konten- und Steuer-Objekte zu prüfen, ob diese im template-Kontenrahmen einem Mandanten zugeordnet waren und dies dann für den neuen Mandanten auch wieder zu tun. Also etwa so:

Zeile 114:
k.setMandant(kt.getMandant() != null ? mandant : null);

Zeile 127:
s.setMandant(st.getMandant() != null ? mandant : null);

2024-06-17 12:41 UTC, lenilsas commented on src/de/willuhn/jameica/fibu/util/BuchungUtil.java
> +        params.add(new Double(start.getTime()));
Bei mir hat das mit McKoi nicht funktioniert. Ich habe gemerkt, dass ein Object erwartet wir, so funktioniert es nun. Bei MySql geht es auch ohne das Double.

2024-06-17 12:44 UTC, lenilsas commented on src/de/willuhn/jameica/fibu/ext/hibiscus/UmsatzListMenu.java
> +      throw new ApplicationException(i18n.tr("Kein offenes Gesch�ftsjahr zum Mandanten im Zeitraum der Buchung"));
Stimmt, bei einer einzelnen Buchung macht das sinn. Ich habe jedoch mehrere Mandanten und wenn beim richtigen Mandanten kein passendes Geschäftsjahr ist, werden alle Buchungen in den falschen Mandanten übernommen. Ich schaue nochmal nach einer lösung.

2024-06-18 05:17 UTC, lenilsas commented on src/de/willuhn/jameica/fibu/gui/controller/KontoControl.java
> +	list.addFilter("mandant_id is null or mandant_id = "+konto.getMandant().getID());
Es wir geprüft, ob die Steuer im richtigen Kontenrahmen ist, jedoch nicht ob es eine Mandantbezogene Steuer ist. Wenn also ein Mandant einen neuen Steuersatz anlegt in einem allgemeinen (nicht Mandantbezogenen) Kontenrahmen, so wird dieser bei allen anderen Mandanten mit gleichem Kontenrahmen angezeigt.

2024-06-18 05:31 UTC, willuhn commented on src/de/willuhn/jameica/fibu/gui/controller/KontoControl.java
> +	list.addFilter("mandant_id is null or mandant_id = "+konto.getMandant().getID());
> Es wir geprüft, ob die Steuer im richtigen Kontenrahmen ist, jedoch nicht ob es eine Mandantbezogene Steuer ist. Wenn also ein Mandant einen neuen Steuersatz anlegt in einem allgemeinen (nicht Mandantbezogenen) Kontenrahmen, so wird dieser bei allen anderen Mandanten mit gleichem Kontenrahmen angezeigt.

Aus meiner Sicht sollte das doch auch so sein. Wenn ein Steuersatz in einem System-Kontenrahmen angelegt wird (egal von welchem Mandanten), dann soll er auch bei jedem Mandanten angezeigt werden. Das ist doch genau der Sinn der System-Daten - dass sie mandantenübergreifend gelten.

2024-06-18 05:41 UTC, lenilsas commented on src/de/willuhn/jameica/fibu/gui/controller/KontoControl.java
> +	list.addFilter("mandant_id is null or mandant_id = "+konto.getMandant().getID());
Ok, das kann man so machen, nur dann finde ich, sollte bei der Steuer auch nicht die mandant_id gespeichert werden. Denn sonst ist sie ja doch einem Mandanten zugeordnet aber für alle verfügbar. (Genauso sehe ich es bei den Konten, auch hier wird in Systemkontenkahmen bei neu angelegten Konten die mandant_id gespeichert)

2024-06-18 06:33 UTC, willuhn commented on src/de/willuhn/jameica/fibu/gui/controller/KontoControl.java
> +	list.addFilter("mandant_id is null or mandant_id = "+konto.getMandant().getID());
> Ok, das kann man so machen, nur dann finde ich, sollte bei der Steuer auch nicht die mandant_id gespeichert werden. Denn sonst ist sie ja doch einem Mandanten zugeordnet aber für alle verfügbar. (Genauso sehe ich es bei den Konten, auch hier wird in Systemkontenkahmen bei neu angelegten Konten die mandant_id gespeichert)

Das stimmt. Der Mandant wird ja grundsätzlich mit gespeichert. Ja, dann macht der zusätzliche Filter tatsächlich sinn.

2024-06-18 07:00 UTC, lenilsas commented on src/de/willuhn/jameica/fibu/ext/hibiscus/UmsatzListMenu.java
> +      throw new ApplicationException(i18n.tr("Kein offenes Gesch�ftsjahr zum Mandanten im Zeitraum der Buchung"));
hier würde ich vorschlagen:
`if (jahr == null){
    if(auto)
        throw new ApplicationException(i18n.tr("Kein offenes Geschäftsjahr zum Mandanten im Zeitraum der Buchung"));
    else
        jahr = Settings.getActiveGeschaeftsjahr();
}`

2024-06-18 07:02 UTC, lenilsas commented on src/de/willuhn/jameica/fibu/gui/controller/KontoControl.java
> +	list.addFilter("mandant_id is null or mandant_id = "+konto.getMandant().getID());
Ich würde das auch bei den Konten so machen, da habe ich jedoch noch keine passende Lösung gefunden

2024-06-18 07:56 UTC, willuhn commented on src/de/willuhn/jameica/fibu/gui/controller/KontoControl.java
> +	list.addFilter("mandant_id is null or mandant_id = "+konto.getMandant().getID());
> Ich würde das auch bei den Konten so machen, da habe ich jedoch noch keine passende Lösung gefunden

Welche Stelle meinst du da genau?

2024-06-18 08:21 UTC, lenilsas commented on src/de/willuhn/jameica/fibu/gui/controller/KontoControl.java
> +	list.addFilter("mandant_id is null or mandant_id = "+konto.getMandant().getID());
In KontenrahmenImpl. Hier habe ich keinen Zugriff auf den Mandanten. Man kann ihn per getActiveGeschaeftsjahr() holen. Das funktioniert aber nicht bei den Einstellungen des Mandanten da hier ja auch ein anderer Mandant aufgerufen sein kann.
```
 /**
   * @see de.willuhn.jameica.fibu.rmi.Kontenrahmen#getKonten()
   */
  public DBIterator getKonten() throws RemoteException
  {
    DBIterator list = getService().createList(Konto.class);
    list.addFilter("(kontenrahmen_id = " + this.getID() + ")");
    list.setOrder(Settings.getAccountOrder());
    return list;
  }
```

2024-06-18 08:30 UTC, willuhn commented on src/de/willuhn/jameica/fibu/gui/controller/KontoControl.java
> +	list.addFilter("mandant_id is null or mandant_id = "+konto.getMandant().getID());
> In KontenrahmenImpl. Hier habe ich keinen Zugriff auf den Mandanten.

Ich würde das so lassen. Aus meiner Sicht ist das korrekt. Die Methode "getKonten()" sollte alle Konten des Kontenrahmens liefern. Egal, was als Mandant im Konto steht. Wenn das Konto im Kontenrahmen ist, sollte es immer angezeigt werden. Klar, könnte es den Fall geben, dass ein Mandant ein Konto im Kontenrahmen eines anderen Mandanten einfügt. Diesen Edge-Case würde ich aber nicht weiter beachten.

2024-06-18 08:34 UTC, lenilsas commented on src/de/willuhn/jameica/fibu/gui/controller/KontoControl.java
> +	list.addFilter("mandant_id is null or mandant_id = "+konto.getMandant().getID());
ok, können wir so lassen. Ich verwende mehrere Mandanten mit dem gleichen Systemkontenrahmen und habe eigene Konten hinzugefügt, da kommt es dann zu dem Problem. Eigentlich hätte ich besser für jeden Mandanten den Kontenrahmen dupliziert, dann bleibt das Problem aus.

2024-06-18 08:41 UTC, willuhn commented on src/de/willuhn/jameica/fibu/gui/controller/KontoControl.java
> +	list.addFilter("mandant_id is null or mandant_id = "+konto.getMandant().getID());
> Eigentlich hätte ich besser für jeden Mandanten den Kontenrahmen dupliziert, dann bleibt das Problem aus.

Korrekt. Das wäre hier der bessere Ansatz gewesen. Wenn man Anpassungen vornimmt am Kontenrahmen vornimmt, dann sollte das ein mandantenspezifischer Kontenrahmen sein. Bei Änderungen am System-Kontenrahmen sollte dem User bewusst sein, dass die Änderungen alle Mandanten betrifft - deshalb ja auch System-Kontenrahmen.

Die grundsätzliche Speicherung der Mandanten-ID im Konto dient eher dazu, dass man anschließend auch in den Systemkontenrahmen noch erkennen kann, welche Konten nachträglich angelegt wurden.

2024-06-19 08:35 UTC, merged